### ISSUE TITLE
Add A License

### ISSUE THREAD

**Issue by jakebasile** [aqualad/brevie-wedding#1]
This repo has no license, so no one knows what they can do with the source. I'd fork and submit a PR, but as there is no source I can't.

I suggest the [AGPL](https://www.gnu.org/licenses/agpl.txt), as it ensures complete software freedom by allowing anyone who attends your wedding the right to view, understand, and modify the wedding. An alternative would be the [WTFPL](http://www.wtfpl.net/) if you prefer your wedding to be avant-garde or the [Apache License](http://www.apache.org/licenses/LICENSE-2.0) if you would like it to be overly wordy.

Also, congratulations.

**Comment by aqualad** [comment]
Haha, fixed.  Thanks!
